version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: it-forever-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: it_forever
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-forever-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - mysql

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: it-forever-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: it-forever-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

  # Mailhog Service
  mailhog:
    image: mailhog/mailhog
    container_name: it-forever-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
